name: Metrics

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: false

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Overview
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: mendsec
          filename: overview.svg
          committer_branch: metrics
          base: header, activity, community, repositories
          config_timezone: Europe/Lisbon
          config_theme: dark

      - name: Languages
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: mendsec
          filename: languages.svg
          committer_branch: metrics
          base: ""
          config_timezone: Europe/Lisbon
          config_theme: dark
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used

      - name: Calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: mendsec
          filename: calendar.svg
          committer_branch: metrics
          base: ""
          config_timezone: Europe/Lisbon
          config_theme: dark
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
